//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RegisterationOfUser.serveraunty {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataUsingDataContractOperationCompleted;
        
        private System.Threading.SendOrPostCallback addrishtaofOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleterishtaofOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginofOperationCompleted;
        
        private System.Threading.SendOrPostCallback editprofileofOperationCompleted;
        
        private System.Threading.SendOrPostCallback approverishtaofOperationCompleted;
        
        private System.Threading.SendOrPostCallback getpaymentofOperationCompleted;
        
        private System.Threading.SendOrPostCallback seekofrishtaOperationCompleted;
        
        private System.Threading.SendOrPostCallback allowofdetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback regofadminOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginofadminOperationCompleted;
        
        private System.Threading.SendOrPostCallback addrishtatobeapprovedofOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::RegisterationOfUser.Properties.Settings.Default.RegisterationOfUser_serveraunty_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event GetDataUsingDataContractCompletedEventHandler GetDataUsingDataContractCompleted;
        
        /// <remarks/>
        public event addrishtaofCompletedEventHandler addrishtaofCompleted;
        
        /// <remarks/>
        public event deleterishtaofCompletedEventHandler deleterishtaofCompleted;
        
        /// <remarks/>
        public event loginofCompletedEventHandler loginofCompleted;
        
        /// <remarks/>
        public event editprofileofCompletedEventHandler editprofileofCompleted;
        
        /// <remarks/>
        public event approverishtaofCompletedEventHandler approverishtaofCompleted;
        
        /// <remarks/>
        public event getpaymentofCompletedEventHandler getpaymentofCompleted;
        
        /// <remarks/>
        public event seekofrishtaCompletedEventHandler seekofrishtaCompleted;
        
        /// <remarks/>
        public event allowofdetailsCompletedEventHandler allowofdetailsCompleted;
        
        /// <remarks/>
        public event regofadminCompletedEventHandler regofadminCompleted;
        
        /// <remarks/>
        public event loginofadminCompletedEventHandler loginofadminCompleted;
        
        /// <remarks/>
        public event addrishtatobeapprovedofCompletedEventHandler addrishtatobeapprovedofCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetData(int value, [System.Xml.Serialization.XmlIgnoreAttribute()] bool valueSpecified) {
            object[] results = this.Invoke("GetData", new object[] {
                        value,
                        valueSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified) {
            this.GetDataAsync(value, valueSpecified, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        value,
                        valueSpecified}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetDataUsingDataContract", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CompositeType GetDataUsingDataContract([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CompositeType composite) {
            object[] results = this.Invoke("GetDataUsingDataContract", new object[] {
                        composite});
            return ((CompositeType)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite, object userState) {
            if ((this.GetDataUsingDataContractOperationCompleted == null)) {
                this.GetDataUsingDataContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractOperationCompleted);
            }
            this.InvokeAsync("GetDataUsingDataContract", new object[] {
                        composite}, this.GetDataUsingDataContractOperationCompleted, userState);
        }
        
        private void OnGetDataUsingDataContractOperationCompleted(object arg) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/addrishtaof", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addrishtaof([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RISHTA r) {
            this.Invoke("addrishtaof", new object[] {
                        r});
        }
        
        /// <remarks/>
        public void addrishtaofAsync(RISHTA r) {
            this.addrishtaofAsync(r, null);
        }
        
        /// <remarks/>
        public void addrishtaofAsync(RISHTA r, object userState) {
            if ((this.addrishtaofOperationCompleted == null)) {
                this.addrishtaofOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddrishtaofOperationCompleted);
            }
            this.InvokeAsync("addrishtaof", new object[] {
                        r}, this.addrishtaofOperationCompleted, userState);
        }
        
        private void OnaddrishtaofOperationCompleted(object arg) {
            if ((this.addrishtaofCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addrishtaofCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/deleterishtaof", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deleterishtaof([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RISHTA r) {
            this.Invoke("deleterishtaof", new object[] {
                        r});
        }
        
        /// <remarks/>
        public void deleterishtaofAsync(RISHTA r) {
            this.deleterishtaofAsync(r, null);
        }
        
        /// <remarks/>
        public void deleterishtaofAsync(RISHTA r, object userState) {
            if ((this.deleterishtaofOperationCompleted == null)) {
                this.deleterishtaofOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleterishtaofOperationCompleted);
            }
            this.InvokeAsync("deleterishtaof", new object[] {
                        r}, this.deleterishtaofOperationCompleted, userState);
        }
        
        private void OndeleterishtaofOperationCompleted(object arg) {
            if ((this.deleterishtaofCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleterishtaofCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/loginof", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void loginof([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool loginofResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool loginofResultSpecified) {
            object[] results = this.Invoke("loginof", new object[] {
                        email,
                        password});
            loginofResult = ((bool)(results[0]));
            loginofResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void loginofAsync(string email, string password) {
            this.loginofAsync(email, password, null);
        }
        
        /// <remarks/>
        public void loginofAsync(string email, string password, object userState) {
            if ((this.loginofOperationCompleted == null)) {
                this.loginofOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginofOperationCompleted);
            }
            this.InvokeAsync("loginof", new object[] {
                        email,
                        password}, this.loginofOperationCompleted, userState);
        }
        
        private void OnloginofOperationCompleted(object arg) {
            if ((this.loginofCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginofCompleted(this, new loginofCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/editprofileof", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void editprofileof() {
            this.Invoke("editprofileof", new object[0]);
        }
        
        /// <remarks/>
        public void editprofileofAsync() {
            this.editprofileofAsync(null);
        }
        
        /// <remarks/>
        public void editprofileofAsync(object userState) {
            if ((this.editprofileofOperationCompleted == null)) {
                this.editprofileofOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditprofileofOperationCompleted);
            }
            this.InvokeAsync("editprofileof", new object[0], this.editprofileofOperationCompleted, userState);
        }
        
        private void OneditprofileofOperationCompleted(object arg) {
            if ((this.editprofileofCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editprofileofCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/approverishtaof", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void approverishtaof([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RISHTA r) {
            this.Invoke("approverishtaof", new object[] {
                        r});
        }
        
        /// <remarks/>
        public void approverishtaofAsync(RISHTA r) {
            this.approverishtaofAsync(r, null);
        }
        
        /// <remarks/>
        public void approverishtaofAsync(RISHTA r, object userState) {
            if ((this.approverishtaofOperationCompleted == null)) {
                this.approverishtaofOperationCompleted = new System.Threading.SendOrPostCallback(this.OnapproverishtaofOperationCompleted);
            }
            this.InvokeAsync("approverishtaof", new object[] {
                        r}, this.approverishtaofOperationCompleted, userState);
        }
        
        private void OnapproverishtaofOperationCompleted(object arg) {
            if ((this.approverishtaofCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.approverishtaofCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/getpaymentof", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getpaymentof(int number, [System.Xml.Serialization.XmlIgnoreAttribute()] bool numberSpecified) {
            this.Invoke("getpaymentof", new object[] {
                        number,
                        numberSpecified});
        }
        
        /// <remarks/>
        public void getpaymentofAsync(int number, bool numberSpecified) {
            this.getpaymentofAsync(number, numberSpecified, null);
        }
        
        /// <remarks/>
        public void getpaymentofAsync(int number, bool numberSpecified, object userState) {
            if ((this.getpaymentofOperationCompleted == null)) {
                this.getpaymentofOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetpaymentofOperationCompleted);
            }
            this.InvokeAsync("getpaymentof", new object[] {
                        number,
                        numberSpecified}, this.getpaymentofOperationCompleted, userState);
        }
        
        private void OngetpaymentofOperationCompleted(object arg) {
            if ((this.getpaymentofCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getpaymentofCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/seekofrishta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RISHTA seekofrishta() {
            object[] results = this.Invoke("seekofrishta", new object[0]);
            return ((RISHTA)(results[0]));
        }
        
        /// <remarks/>
        public void seekofrishtaAsync() {
            this.seekofrishtaAsync(null);
        }
        
        /// <remarks/>
        public void seekofrishtaAsync(object userState) {
            if ((this.seekofrishtaOperationCompleted == null)) {
                this.seekofrishtaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnseekofrishtaOperationCompleted);
            }
            this.InvokeAsync("seekofrishta", new object[0], this.seekofrishtaOperationCompleted, userState);
        }
        
        private void OnseekofrishtaOperationCompleted(object arg) {
            if ((this.seekofrishtaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.seekofrishtaCompleted(this, new seekofrishtaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/allowofdetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void allowofdetails() {
            this.Invoke("allowofdetails", new object[0]);
        }
        
        /// <remarks/>
        public void allowofdetailsAsync() {
            this.allowofdetailsAsync(null);
        }
        
        /// <remarks/>
        public void allowofdetailsAsync(object userState) {
            if ((this.allowofdetailsOperationCompleted == null)) {
                this.allowofdetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnallowofdetailsOperationCompleted);
            }
            this.InvokeAsync("allowofdetails", new object[0], this.allowofdetailsOperationCompleted, userState);
        }
        
        private void OnallowofdetailsOperationCompleted(object arg) {
            if ((this.allowofdetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.allowofdetailsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/regofadmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void regofadmin([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AUNTY a) {
            this.Invoke("regofadmin", new object[] {
                        a});
        }
        
        /// <remarks/>
        public void regofadminAsync(AUNTY a) {
            this.regofadminAsync(a, null);
        }
        
        /// <remarks/>
        public void regofadminAsync(AUNTY a, object userState) {
            if ((this.regofadminOperationCompleted == null)) {
                this.regofadminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregofadminOperationCompleted);
            }
            this.InvokeAsync("regofadmin", new object[] {
                        a}, this.regofadminOperationCompleted, userState);
        }
        
        private void OnregofadminOperationCompleted(object arg) {
            if ((this.regofadminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.regofadminCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/loginofadmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void loginofadmin([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AUNTY b, out bool loginofadminResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool loginofadminResultSpecified) {
            object[] results = this.Invoke("loginofadmin", new object[] {
                        b});
            loginofadminResult = ((bool)(results[0]));
            loginofadminResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void loginofadminAsync(AUNTY b) {
            this.loginofadminAsync(b, null);
        }
        
        /// <remarks/>
        public void loginofadminAsync(AUNTY b, object userState) {
            if ((this.loginofadminOperationCompleted == null)) {
                this.loginofadminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginofadminOperationCompleted);
            }
            this.InvokeAsync("loginofadmin", new object[] {
                        b}, this.loginofadminOperationCompleted, userState);
        }
        
        private void OnloginofadminOperationCompleted(object arg) {
            if ((this.loginofadminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginofadminCompleted(this, new loginofadminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/addrishtatobeapprovedof", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addrishtatobeapprovedof([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RISHTA r) {
            this.Invoke("addrishtatobeapprovedof", new object[] {
                        r});
        }
        
        /// <remarks/>
        public void addrishtatobeapprovedofAsync(RISHTA r) {
            this.addrishtatobeapprovedofAsync(r, null);
        }
        
        /// <remarks/>
        public void addrishtatobeapprovedofAsync(RISHTA r, object userState) {
            if ((this.addrishtatobeapprovedofOperationCompleted == null)) {
                this.addrishtatobeapprovedofOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddrishtatobeapprovedofOperationCompleted);
            }
            this.InvokeAsync("addrishtatobeapprovedof", new object[] {
                        r}, this.addrishtatobeapprovedofOperationCompleted, userState);
        }
        
        private void OnaddrishtatobeapprovedofOperationCompleted(object arg) {
            if ((this.addrishtatobeapprovedofCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addrishtatobeapprovedofCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/serveraunty")]
    public partial class CompositeType {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private string stringValueField;
        
        /// <remarks/>
        public bool BoolValue {
            get {
                return this.boolValueField;
            }
            set {
                this.boolValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified {
            get {
                return this.boolValueFieldSpecified;
            }
            set {
                this.boolValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/serveraunty")]
    public partial class AUNTY {
        
        private string codeField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/serveraunty")]
    public partial class RISHTA {
        
        private string ageField;
        
        private bool allowedcontactField;
        
        private bool allowedcontactFieldSpecified;
        
        private string castField;
        
        private string cityField;
        
        private string contactField;
        
        private string emailField;
        
        private string fatherNameField;
        
        private string genderField;
        
        private string heightField;
        
        private string incomeField;
        
        private string nameField;
        
        private string passwordField;
        
        private string professionField;
        
        private string religionField;
        
        private bool rishtacameField;
        
        private bool rishtacameFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        public bool Allowedcontact {
            get {
                return this.allowedcontactField;
            }
            set {
                this.allowedcontactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowedcontactSpecified {
            get {
                return this.allowedcontactFieldSpecified;
            }
            set {
                this.allowedcontactFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cast {
            get {
                return this.castField;
            }
            set {
                this.castField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FatherName {
            get {
                return this.fatherNameField;
            }
            set {
                this.fatherNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Income {
            get {
                return this.incomeField;
            }
            set {
                this.incomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Profession {
            get {
                return this.professionField;
            }
            set {
                this.professionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Religion {
            get {
                return this.religionField;
            }
            set {
                this.religionField = value;
            }
        }
        
        /// <remarks/>
        public bool Rishtacame {
            get {
                return this.rishtacameField;
            }
            set {
                this.rishtacameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RishtacameSpecified {
            get {
                return this.rishtacameFieldSpecified;
            }
            set {
                this.rishtacameFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetDataUsingDataContractCompletedEventHandler(object sender, GetDataUsingDataContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompositeType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompositeType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void addrishtaofCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void deleterishtaofCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void loginofCompletedEventHandler(object sender, loginofCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginofCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginofCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool loginofResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool loginofResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void editprofileofCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void approverishtaofCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void getpaymentofCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void seekofrishtaCompletedEventHandler(object sender, seekofrishtaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class seekofrishtaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal seekofrishtaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RISHTA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RISHTA)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void allowofdetailsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void regofadminCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void loginofadminCompletedEventHandler(object sender, loginofadminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginofadminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginofadminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool loginofadminResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool loginofadminResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void addrishtatobeapprovedofCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591